title: Startup Mom
header-image: /assets/img/startup_mom.jpg
image:
  path: /assets/img/startup_mom.jpg
  height: 100
  width: 100
twitter_username: "tamarucham"
markdown: kramdown
url: "https://blog.parentscheduler.app"
baseurl: ""
psurl: https://parentscheduler.app/
theme: null

# for atom feed
author:
  name: Tamar Rucham
  email: tamar@parentscheduler.app
  image: "https://s.gravatar.com/avatar/b6082a5ffd214b4b6151900dd3d4d2a2?s=80" 
  email: tamar@parentscheduler.app

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-analytics

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/

jekyll_analytics:
  GoogleAnalytics:
    id: UA-171797937-1
    anonymizeIp: true